<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Duong" failures="2" tests="10" name="phonesystem.edu.dao.SanPhamDAOTest" time="0.853" errors="0" timestamp="15 Apr 2023 01:07:57 GMT">
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testDelete_SanPham on testDelete_SanPham(phonesystem.edu.dao.SanPhamDAOTest)" time="0.407"/>
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testUpdateValid on testUpdateValid(phonesystem.edu.dao.SanPhamDAOTest)" time="0.419"/>
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testInsertValid on testInsertValid(phonesystem.edu.dao.SanPhamDAOTest)" time="0.468">
    <failure type="java.lang.RuntimeException" message="com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint &amp;apos;PK__SanPham__FAC7442D10756ABE&amp;apos;. Cannot insert duplicate key in object &amp;apos;dbo.SanPham&amp;apos;. The duplicate key value is (SP020).">
      <![CDATA[java.lang.RuntimeException: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK__SanPham__FAC7442D10756ABE'. Cannot insert duplicate key in object 'dbo.SanPham'. The duplicate key value is (SP020).
at phonesystem.edu.ultil.jdbcHelper.update(jdbcHelper.java:56)
at phonesystem.edu.dao.SanPhamDAO.insert(SanPhamDAO.java:40)
at phonesystem.edu.dao.SanPhamDAOTest.testInsertValid(SanPhamDAOTest.java:60)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Violation of PRIMARY KEY constraint 'PK__SanPham__FAC7442D10756ABE'. Cannot insert duplicate key in object 'dbo.SanPham'. The duplicate key value is (SP020).
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:600)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7225)
at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3053)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeUpdate(SQLServerPreparedStatement.java:471)
at phonesystem.edu.ultil.jdbcHelper.update(jdbcHelper.java:53)
... 46 more
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testInsertValid on testInsertValid(phonesystem.edu.dao.SanPhamDAOTest) -->
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testUpdate_trangThai on testUpdate_trangThai(phonesystem.edu.dao.SanPhamDAOTest)" time="0.564"/>
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testSelect_All_TheoTenSP on testSelect_All_TheoTenSP(phonesystem.edu.dao.SanPhamDAOTest)" time="0.681"/>
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testRestore on testRestore(phonesystem.edu.dao.SanPhamDAOTest)" time="0.707"/>
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testUpdateisNull on testUpdateisNull(phonesystem.edu.dao.SanPhamDAOTest)" time="0.732"/>
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testInsertIsNull on testInsertIsNull(phonesystem.edu.dao.SanPhamDAOTest)" time="0.732">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;phonesystem.edu.entity.SanPham.getMaSanPham()&amp;quot; because &amp;quot;entity&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "phonesystem.edu.entity.SanPham.getMaSanPham()" because "entity" is null
at phonesystem.edu.dao.SanPhamDAO.insert(SanPhamDAO.java:41)
at phonesystem.edu.dao.SanPhamDAOTest.testInsertIsNull(SanPhamDAOTest.java:51)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- testInsertIsNull on testInsertIsNull(phonesystem.edu.dao.SanPhamDAOTest) -->
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testUpdate_SoLuong on testUpdate_SoLuong(phonesystem.edu.dao.SanPhamDAOTest)" time="0.754"/>
  <testcase classname="phonesystem.edu.dao.SanPhamDAOTest" name="testSelectByid on testSelectByid(phonesystem.edu.dao.SanPhamDAOTest)" time="0.779"/>
</testsuite> <!-- phonesystem.edu.dao.SanPhamDAOTest -->
